In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

In [24]:
df = pd.read_excel("..//Data/ENB2012_data.xlsx")

In [25]:
df.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

No label for the Columns, adding names

In [26]:
df.columns = ["Relative_Compactness","Surface_Area","Wall_Area","Roof_Area","Overall_Height","Orientation","Glazing_Area","Glazing_Distribution","Heating_Load","Cooling_Load"]

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Relative_Compactness  768 non-null    float64
 1   Surface_Area          768 non-null    float64
 2   Wall_Area             768 non-null    float64
 3   Roof_Area             768 non-null    float64
 4   Overall_Height        768 non-null    float64
 5   Orientation           768 non-null    int64
 6   Glazing_Area          768 non-null    float64
 7   Glazing_Distribution  768 non-null    int64
 8   Heating_Load          768 non-null    float64
 9   Cooling_Load          768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB

From explore, its clear that the data have no null value.
The zero in certain feature is needed.
There is no specific outliers since data is generated within set enviroment.
To Do-
1- Seperate the data into 2 sets by height
2- Drop Surface_Area - it have direct relationship to Relative_com and Wall and Roof
3- Orientation, Glazing_area, Glazing Distribution needs to be dummied

In [28]:
df.drop(columns=['Surface_Area'], inplace=True)

In [29]:
dfd = pd.get_dummies(df, columns=['Orientation'],prefix="Ori", drop_first=True)
dfd = pd.get_dummies(dfd, columns=['Glazing_Area'],prefix="GA", drop_first=True)
dfd = pd.get_dummies(dfd, columns=['Glazing_Distribution'],prefix="GD",drop_first=True)

Note that name for the dummy columns are shortened.
Ori-Orintation
GA-GlazingArea
GD-GlazingDistribution

In [30]:
df7=dfd[dfd['Overall_Height']==7]
df35=dfd[dfd['Overall_Height']==3.5]

Created new dataframes, seperated by the height

In [31]:
df7.drop('Overall_Height', axis=1, inplace=True)
df35.drop('Overall_Height', axis=1, inplace=True)

Rmoved the height columns since now the data is seperated by the height

In [32]:
df7.head()

,Relative_Compactness,Wall_Area,Roof_Area,Heating_Load,Cooling_Load,Ori_3,Ori_4,Ori_5,GA_0.1,GA_0.25,GA_0.4,GD_1,GD_2,GD_3,GD_4,GD_5
0,0.98,294.0,110.25,15.55,21.33,False,False,False,False,False,False,False,False,False,False,False
1,0.98,294.0,110.25,15.55,21.33,True,False,False,False,False,False,False,False,False,False,False
2,0.98,294.0,110.25,15.55,21.33,False,True,False,False,False,False,False,False,False,False,False
3,0.98,294.0,110.25,15.55,21.33,False,False,True,False,False,False,False,False,False,False,False
4,0.90,318.5,122.50,20.84,28.28,False,False,False,False,False,False,False,False,False,False,False

TO confirm
-Surface Area Removed
-Height Removed
-Orientation, Glazing Area, Glazing Dis all dummied

In [33]:
df.to_csv('../Data/Cleaned_Data.csv', index=False)
df7.to_csv('../Data/Cleaned_Data7.csv', index=False)
df35.to_csv('../Data/Cleaned_Data35.csv', index=False)

To save the cleaned and transformed dataset as new csv file 
Created Clean Data, which dropped Surface Area and kept all the values, not dummied.
The Data7